---
title: "R Notebook"
output: html_notebook
---

```{r data-splitting}

library(caret)
library(kernlab)
data(spam)
inTrain=createDataPartition(y=spam$type,p=0.75,list=FALSE)
training<-spam[inTrain,]
testing<-spam[-inTrain,]
dim(training)
dim(testing)
```
```{r fitting a model}

set.seed(3443)
modelFit<- train(type~.,data=training, method="glm")
modelFit$finalModel

# Some comments
# ~. is used for choosing all the variables in the dataset to make a prediction of the output variable "type"
# We can look at the model parameters by using the "finalmodel" command

```

```{r predict}
prediction<-predict(modelFit,newdata=testing)
prediction

```


```{r confusion matrix}
conf_matrix=confusionMatrix(prediction,testing$type)
conf_matrix
```
```{r k-fold cross validation}

set.seed(32323)
folds <- createFolds(spam$type,k=10,list=TRUE,returnTrain = TRUE) 
sapply(folds, length)

# The return values of the different folds are the indices corresponding to the training data set in that fold
```

```{r time-slicing}
set.seed(32323)
tme<- 1:10000
folds<-createTimeSlices(y=tme, initialWindow = 20, horizon=10)
names(folds)
folds$train[[1]]

#Time slicing can be used when we want to use time series forecasting. The initial window contains the number of #samples that will be used to predict the next number of samples whcich are stored in the horizon variable
```


```{r preprocessing}

# before training, we now preprocess the data by scaling it and making it's mean equal to 1
set.seed(32323)
modelFit <-  train(type ~., data= training, preProcess=c("center","scale"),method="glm")
modelFit


```

```{r preprocessing with PCA}

M <- abs(cor(training[,-58])) # take the correlation of each variable with each other
diag(M) <- 0 # because the correlation of each variable with itself is 1
R <- which(M>0.8, arr.ind = T)
plot(spam[,34],spam[,32])
plot(spam[,40],spam[,32])
plot(spam[,34],spam[,40])
R
 # plotting the highly correlated variables


#spam_small <- spam[,c(34,32)]
spam_small <- log10 ((spam[,-58] )+1)
prCom <- prcomp(spam_small)
colourtype <- ((spam$type=="spam")*1+1)
plot(prCom$x[,1],prCom$x[,2], col=colourtype,xlab='PC1', ylab= 'PC2'  )
summary(prCom)
```



```{r princial components}
summary(prCom)

prCom$rotation
```














